// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'api_key',
    appId: '1:115044394622:android:7107e14f51ba5aa7e59a2f',
    messagingSenderId: '115044394622',
    projectId: 'solvednow-d1aa4',
    storageBucket: 'solvednow-d1aa4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'api_key',
    appId: '1:115044394622:ios:1ef87e878abe2770e59a2f',
    messagingSenderId: '115044394622',
    projectId: 'solvednow-d1aa4',
    storageBucket: 'solvednow-d1aa4.appspot.com',
    iosBundleId: 'dev.arpaap.solvedNow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'api_key',
    appId: '1:115044394622:ios:8a728da11f2d2dd7e59a2f',
    messagingSenderId: '115044394622',
    projectId: 'solvednow-d1aa4',
    storageBucket: 'solvednow-d1aa4.appspot.com',
    iosBundleId: 'dev.arpaap.solvedNow.RunnerTests',
  );
}
